name: coverde
description: A CLI for basic coverage trace files manipulation. Validate minimum coverage, filter trace files data by tested file paths and generate HTML coverage reports.
version: 0.2.0+2
homepage: https://github.com/mrverdant13/coverde
repository: https://github.com/mrverdant13/coverde/tree/main/packages/coverde_cli
issue_tracker: https://github.com/mrverdant13/coverde/issues
topics:
  - test
  - testing
  - coverage
  - lcov
screenshots:
  - description: Coverage report example (directory)
    path: doc/report_directory_example.png
  - description: Coverage report example (file)
    path: doc/report_file_example.png
  - description: Coverage check example (passing)
    path: doc/check_result_pass.png
  - description: Coverage check example (failing)
    path: doc/check_result_fail.png

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  html: ^0.15.4
  io: ^1.0.4
  meta: ^1.9.1
  path: ^1.8.3
  process: ">=5.0.2 <6.0.0"
  pub_updater: ">=0.3.1 <0.5.0"
  universal_io: ^2.2.2

dev_dependencies:
  build: ^2.4.1
  build_config: ^1.1.1
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  csslib: ^1.0.0
  mocktail: ^1.0.0
  package_assets_generator:
    path: ../package_assets_generator
  package_data_generator:
    path: ../package_data_generator
  pubspec_parse: ^1.2.3
  test: ^1.24.6
  very_good_analysis: ^5.0.0+1

executables:
  coverde:
